### ISSUE TITLE
Add undergrads to "About" page

### ISSUE THREAD

**Issue by whatknows** [cu-idlab/lab-www#2]
#mediumishpriority

Can we add the undergrads who work with us to the about page? I am thinking just a list of people, not huge bios.

Here is a list from my CV:
Ian Fawaz, B.S., Computer Science
Amjad Alharbi, B.S., Computer Science
Tom Slesinger, B.S., Information Science
Jacob Paul, B.S., Information Science
Elliot Huey, B.A., Media Studies
Chris Koehler, B.S., Information Science
Josh McCann, B.S., Computer Science
Kyle Frye, B.S., Information Science

**Comment by aaroniidx** [comment]
Done :)
